apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: fluentbit-only
  name: postgresql
  namespace: fluent
spec:
  customPlugin:
    config: |
      Name                pgsql
      Match               *
      Host                cnpg-cluster-rw.cnpg-system.svc.cluster.local
      Port                5432
      User                kmontocam
      Password            ...
      Database            kmontocam
      Table               fluentbit
      Connection_Options  -c statement_timeout=0
      Timestamp_Key       ts
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBitConfig
metadata:
  labels:
    app.kubernetes.io/name: fluent-bit
  name: fluent-bit-config
  namespace: fluent
spec:
  clusterMultilineParserSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
  clusterParserSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
  filterSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
  multilineParserSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
  outputSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
  parserSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
  service:
    httpServer: true
    parsersFiles:
      - parsers.conf
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterParser
metadata:
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: fluentbit-only
  name: logfmt
spec:
  logfmt: {}
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  labels:
    fluentbit.fluent.io/component: logging
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: fluentbit-only
  name: cluster-filter
spec:
  filters:
    - kubernetes:
        annotations: false
        k8sLoggingExclude: true
        k8sLoggingParser: true
        labels: true
        mergeLog: true
        mergeLogKey: data
    - grep:
        regex: $kubernetes['labels']['devops.kmontocam.com/parse-logs'] true
  match: kube.*
