apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      kmontocam.com/environment: prod
    includeTemplates: true

secretGenerator:
  - name: cloudflare-kmontocam-api
    namespace: cloudflare-operator-system
    envs:
      - .env.cloudflare # must include CLOUDFLARE_API_TOKEN, CLOUDFLARE_API_KEY
  - name: ddclient-ddns
    namespace: kmontocam
    envs:
      - .env.ddclient # must include password
generatorOptions:
  disableNameSuffixHash: true
