apiVersion: v1
kind: ConfigMap
metadata:
  name: ddclient-ddns
  namespace: kmontocam
  labels:
    devops.kmontocam.com: "true"
    devops.kmontocam.com/service: ddclient
data:
  ddclient.conf: |
    ssl=yes
    use=web
    web='https://cloudflare.com/cdn-cgi/trace'
    web-skip='ip='

    protocol=cloudflare, \
    zone=kmontocam.com, \
    ttl=1,
    password_env=DDCLIENT_PASSWORD
    ddns.kmontocam.com
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddclient-ddns
  namespace: kmontocam
  labels:
    devops.kmontocam.com: "true"
    devops.kmontocam.com/service: ddclient
spec:
  timeZone: "America/Monterrey"
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 16 # force end since ddclient process does
      template:
        metadata:
          labels:
            devops.kmontocam.com: "true"
            devops.kmontocam.com/service: ddclient
        spec:
          initContainers:
            - name: ddconfig
              image: busybox
              command:
                - sh
                - -c
                - |
                  cp /tmp/ddclient.conf /config/ddclient.conf
              volumeMounts:
                - name: ddclient-config
                  mountPath: /tmp
                - name: config
                  mountPath: /config
          containers:
            - name: ddclient
              image: lscr.io/linuxserver/ddclient:3.11.2
              imagePullPolicy: IfNotPresent
              env:
                - name: DDCLIENT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: ddclient-ddns
              volumeMounts:
                - name: config
                  mountPath: /config
          volumes:
            - name: ddclient-config
              configMap:
                name: ddclient-ddns
            - name: config
              emptyDir: {}
          restartPolicy: OnFailure
          nodeSelector:
            kubernetes.io/os: linux
