apiVersion: v1
data:
  ddclient.conf: |
    ssl=yes
    use=web
    web='https://cloudflare.com/cdn-cgi/trace'
    web-skip='ip='

    protocol=cloudflare, \
    zone=kmontocam.com, \
    ttl=1,
    password_env=DDCLIENT_PASSWORD
    ddns.kmontocam.com
kind: ConfigMap
metadata:
  labels:
    devops.kmontocam.com: "true"
    devops.kmontocam.com/service: ddclient
  name: ddclient-ddns
  namespace: kmontocam
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    devops.kmontocam.com: "true"
    devops.kmontocam.com/service: ddclient
  name: ddclient-ddns
  namespace: kmontocam
spec:
  jobTemplate:
    spec:
      activeDeadlineSeconds: 16 # force end since ddclient process does
      template:
        metadata:
          labels:
            devops.kmontocam.com: "true"
            devops.kmontocam.com/service: ddclient
        spec:
          containers:
            - env:
                - name: DDCLIENT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: ddclient-ddns
              image: lscr.io/linuxserver/ddclient:3.11.2
              imagePullPolicy: IfNotPresent
              name: ddclient
              volumeMounts:
                - mountPath: /config
                  name: config
          initContainers:
            - command:
                - sh
                - -c
                - |
                  cp /tmp/ddclient.conf /config/ddclient.conf
              image: busybox
              name: ddconfig
              volumeMounts:
                - mountPath: /tmp
                  name: ddclient-config
                - mountPath: /config
                  name: config
          nodeSelector:
            kubernetes.io/os: linux
          restartPolicy: OnFailure
          volumes:
            - configMap:
                name: ddclient-ddns
              name: ddclient-config
            - emptyDir: {}
              name: config
  schedule: "*/5 * * * *"
  timeZone: America/Monterrey
