# NOTE: requires manual installation of cloudflare-operator: https://github.com/adyanth/cloudflare-operator
# kubectl apply -k https://github.com/adyanth/cloudflare-operator/config/default
apiVersion: v1 # TODO: move namespace declaration from pv's
kind: Namespace
metadata:
  labels:
    api.kmontocam.com: "true"
    devops.kmontocam.com: "true"
  name: cloudflare-operator-system
---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: ClusterTunnel
metadata:
  labels:
    api.kmontocam.com: "true"
    devops.kmontocam.com: "true"
  name: rpi5-k3s-cluster
  namespace: cloudflare-operator-system
spec:
  cloudflare:
    accountId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    accountName: kmontocam
    domain: kmontocam.com
    email: kmontocam@outlook.com
    secret: cloudflare-kmontocam-api
  newTunnel:
    name: rpi5-k3s-cluster
  size: 1
---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  labels:
    api.kmontocam.com: "true"
  name: rpi5-k3s-ingress-api
  namespace: ingress-nginx
subjects:
  - name: api
    spec:
      fqdn: api.kmontocam.com
      protocol: http
      target: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
tunnelRef:
  disableDNSUpdates: false
  kind: ClusterTunnel
  name: rpi5-k3s-cluster
---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  labels:
    devops.kmontocam.com: "true"
  name: rpi5-k3s-ingress-devops
  namespace: ingress-nginx
subjects:
  - name: devops
    spec:
      fqdn: devops.kmontocam.com
      protocol: http
      target: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
tunnelRef:
  disableDNSUpdates: false
  kind: ClusterTunnel
  name: rpi5-k3s-cluster
